package lk.banking.timer;

import jakarta.ejb.Local;
import lk.banking.core.dto.DailyReportDto;

import java.time.LocalDate;

@Local
public interface DailyReportService {
    /**
     * Generates a daily report for a specific date.
     * This method is intended to be called by the web layer or other services.
     * @param date The date for which to generate the report.
     * @return A DailyReportDto containing the report data.
     */
    DailyReportDto generateReportForDate(LocalDate date);

    /**
     * Retrieves the daily report that was automatically generated by the timer for the previous day.
     * This might involve storing the last generated report or simply calculating for yesterday.
     * @return A DailyReportDto for the previous day.
     */
    DailyReportDto getYesterdayReport();
}